config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update]
  resources :musics do
    collection do
      get :search
      get :index_autocomplete
      post :publish
      post :unpublish
    end

    member do
      post :convert_to_public
    end
    resources :memories, only: %i[create edit update destroy], shallow: true
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :playlists do
    collection do
      post :add_music_to_playlist
      get :search_for_new
    end

    member do
      get :search_for_edit
      delete :remove_music_from_playlist
    end
  end
  resources :notifications, only: %i[update] do
    collection do
      delete :mark_all_as_read
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :music, touch: true
  has_one :notification, as: :notifiable, dependent: :destroy
  counter_culture :music
  validates :body, presence: true, length: { maximum: 65_535 }

  def create_notification_comment!(current_user, comment_id)
    # MUのユーザーに通知を送る
    save_notification_comment!(current_user, comment_id, music.user_id)

    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    other_commenters_ids = Comment.select(:user_id).where(music_id:).where.not(user_id: current_user.id).distinct.pluck(:user_id)

    # 各コメントユーザーに対して通知を作成
    other_commenters_ids.each do |commenter_id|
      save_notification_comment!(current_user, comment_id, commenter_id)
    end
  end

  def save_notification_comment!(current_user, _comment_id, recipient_id)
    notification = Notification.new(
      sender_id: current_user.id,
      recipient_id:,
      notifiable: self
    )

    # 自分の投稿に対するコメントの場合は、既読とする
    notification.unread = false if notification.sender_id == notification.recipient_id

    # 通知を保存（バリデーションが成功する場合のみ）
    notification.save if notification.valid?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
    @comment = Comment.find(params[:id])
    unless current_user == @comment.user
      flash[:error] = '編集権限がありません'
      redirect_to root_path
    end
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      @comment.create_notification_comment!(current_user, @comment.id)
      flash.now[:success] = 'コメントを追加しました'
    else
      flash.now[:error] = 'コメントを追加できませんでした'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(params.require(:comment).permit(:body))
      flash[:success] = 'コメントを更新しました'
      redirect_to music_path(@comment.music)
    else
      flash.now[:error] = 'コメントの更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    flash.now[:success] = 'コメントを削除しました'
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(music_id: params[:music_id])
  end
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="bg-base-100 my-2">
    <div class="bg-base-300 border-bg-100 p-3 rounded-lg">
      <%= link_to user_path(comment.user) do %>
        <div class="flex">
          <p class="mr-3 rounded-full">
            <% if comment.user.avatar? %>
              <div class="avatar">
                <div class="rounded-full">
                  <%= image_tag comment.user.avatar.url(:avatar) %>
                </div>
              </div>
            <% else %>
              <%= image_tag "default_avatar.png", size: "40x40" %>
            <% end %>
          </p>
          <p class="p-2 link">  <%= comment.user.name %> </p>
        </div>
      <% end %>
      <%= raw Rinku.auto_link(h(comment.body).gsub(/\n/, '<br>'), :urls, 'target="_blank" rel="noopener noreferrer"') %>
      <div class="object-right-top">
        <% if logged_in? && current_user.own?(comment) %>
          <%= link_to "削除", comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "本当にこのコメントを削除しますか？" }, class: "btn btn-sm btn-error float-right" %>
          <%= link_to "編集", edit_comment_path(comment), class: "btn btn-sm btn-secondary mx-2 float-right" %>
        <% end %>
      </div>
      <p class="text-right"><%= l comment.created_at, format: :long %></p>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div id="comment-form", data-controller="textarea", class="w-full flex flex-col">
  <%= form_with model: comment, url: [music, comment], data: { turbo_method: :post } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div>
      <%= f.text_area :body, data: { textarea_target: "textarea" }, class: "w-[18rem] sm:w-[32rem] min-h-24 bg-base-300 textarea textarea-bordered my-2 p-1 rounded-lg" %>
    </div>
    <%= f.submit "追加する", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update "flash_messages", partial: "shared/flash_messages" %>

<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, music: @comment.music %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "comments-list" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, music: @comment.music %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.update "flash_messages", partial: "shared/flash_messages" %>
<%= turbo_stream.remove "comment-#{@comment.id}" do %>
<% end %>

app/views/comments/edit.html.erb
<% set_meta_tags title: t('.title') %>
<div class="h-screen" data-controller="textarea">
  <h1 class="text-center py-4 text-2xl">コメント編集</h1>
  <%= form_with model: @comment, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_area :body, data: { textarea_target: "textarea" }, class: "w-full min-h-24 my-2 bg-base-300 textarea textarea-bordered p-1 rounded-lg"%>
    <%= f.submit "編集完了", class: "btn btn-primary" %>
  <% end %>
</div>