config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update]
  resources :musics do
    collection do
      get :search
      get :index_autocomplete
      post :publish
      post :unpublish
    end

    member do
      post :convert_to_public
    end
    resources :memories, only: %i[create edit update destroy], shallow: true
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :playlists do
    collection do
      post :add_music_to_playlist
      get :search_for_new
    end

    member do
      get :search_for_edit
      delete :remove_music_from_playlist
    end
  end
  resources :notifications, only: %i[update] do
    collection do
      delete :mark_all_as_read
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/views/shared/_before_login_header.html.erb
<header class="py-4 flex items-center justify-between">
  <div>
    <%= link_to root_path do %>
      <%= image_tag "Logo.png", size: "100x100"%>
    <% end %>
  </div>

  <nav class="mr-2 flex items-center">
    <div class="dropdown">
      <div tabindex="0" role="button" class="sm:btn-md btn btn-sm btn-outline btn-primary mr-2">みんなのMU ▼</div>
      <ul tabindex="0" class="dropdown-content menu bg-neutral rounded-box z-[1] w-52 p-2 shadow">
        <li class="link link-primary m-1"><%= link_to "みんなのMU", musics_path %></li>
        <li class="link link-success m-1"><%= link_to "みんなのプレイリスト", playlists_path %></li>
      </ul>
    </div>
    <%= link_to "ログイン", login_path, class: "btn btn-sm btn-secondary btn-outline mr-2 sm:btn-md" %>

    <div class="sm:hidden dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
      </div>
      <ul tabindex="0" class="dropdown-content z-[1] bg-neutral p-2 shadow bg-base-100 rounded-box w-52">
        <%= link_to "利用規約", terms_path, class: "btn btn-link btn-sm" %>
        <%= link_to "プライバシーポリシー", privacy_policy_path, class: "btn btn-link btn-sm" %>
        <%= link_to "お問い合わせ", "https://forms.gle/ngwcLGRTNanH5ahc7", target: "_blank", class: "btn btn-link btn-sm" %>
        <p>© 2024 - STAY with MU</p>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div role="alert" class="alert alert-error flex flex-col my-3">
    <% object.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% case message_type %>
  <% when "info"%>
    <div role="alert" class="alert alert-info flex animate-slide-out-top">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
      <span><%= message %></span>
    </div>
  <% when "success" %>
    <div role="alert" class="alert alert-success flex animate-slide-out-top">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span><%= message %></span>
    </div>
  <% when "warnig" %>
    <div role="alert" class="alert alert-warning flex animate-slide-out-top">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
      <span><%= message %></span>
    </div>
  <% when "error" %>
    <div role="alert" class="alert alert-error flex animate-slide-out-top">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span><%= message %></span>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-center container mx-auto mb-5">
  <nav class="flex flex-wrap justify-center">
    <%= link_to "利用規約", terms_path, class: "btn btn-link btn-sm" %>
    <%= link_to "プライバシーポリシー", privacy_policy_path, class: "btn btn-link btn-sm" %>
    <%= link_to "お問い合わせ", "https://forms.gle/ngwcLGRTNanH5ahc7", target: "_blank", class: "btn btn-link btn-sm" %>
  </nav>
  <aside>
    <p>© 2024 - STAY with MU</p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<header class="py-4 flex items-center justify-between">
  <div>
    <%= link_to root_path do %>
      <%= image_tag "Logo.png", size: "100x100"%>
    <% end %>
  </div>
  <nav class="mr-2 flex">
    <div class="hidden sm:flex">
      <%= link_to "みんなのMU", musics_path, data: { action: "click->modal#checkClick"}, class: "btn btn-primary btn-outline mr-2" %>
      <%= link_to "MUをつくる", new_music_path, class: "btn btn-secondary btn-outline mr-2" %>
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn btn-outline btn-success mr-2">プレイリスト ▼</div>
        <ul tabindex="0" class="dropdown-content menu bg-neutral rounded-box z-[1] w-52 p-2 shadow">
          <li class="link m-1"><%= link_to "みんなのプレイリスト", playlists_path %></li>
          <li class="link m-1"><%= link_to "プレイリストをつくる", new_playlist_path %></li>
        </ul>
      </div>
      <%= link_to user_path(current_user), class: "flex flex-col btn btn-outline" do %>
        <% if current_user.avatar? %>
          <div class="avatar">
            <div class="rounded-full">
              <%= image_tag current_user.avatar.url(:avatar) %>
            </div>
          </div>
          <% else %>
            <%= image_tag "default_avatar.png", size: "40x40" %>
          <% end %>
        <p class="text-xs">マイページ</p>
      <% end %>
    </div>

    <button class="sm:hidden btn btn-ghost" onclick="my_modal_3.showModal()">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-lightbulb" viewBox="0 0 16 16">
        <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a1.964 1.964 0 0 0-.453-.618A5.984 5.984 0 0 1 2 6zm6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1z"/>
      </svg>
    </button>

    <%= render "shared/howto_install" %>

    <div class="dropdown dropdown-end">
      <div tabindex="0" class="btn btn-ghost">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
          <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
        </svg>
          <%= render 'notifications/notification_count' %>
      </div>
      <ul tabindex="0" class="dropdown-content z-[1] p-2 bg-neutral rounded-box w-[18rem] sm:w-[28rem]">
        <%= render 'shared/notifications_dropdown' %>
      </ul>
    </div>

    <div class="sm:hidden dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
      </div>
      <ul tabindex="0" class="dropdown-content z-[1] bg-neutral p-2 shadow bg-base-100 rounded-box w-52">
        <%= link_to "利用規約", terms_path, class: "btn btn-link btn-sm" %>
        <%= link_to "プライバシーポリシー", privacy_policy_path, class: "btn btn-link btn-sm" %>
        <%= link_to "お問い合わせ", "https://forms.gle/ngwcLGRTNanH5ahc7", target: "_blank", class: "btn btn-link btn-sm" %>
        <p>© 2024 - STAY with MU</p>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_howto_install.html.erb
<dialog id="my_modal_3" class="modal">
  <div class="modal-box">
    <form method="dialog">
      <button class="btn btn-circle btn-outline absolute right-2 top-2">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-6 w-6"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
    </form>
    <div class="py-6 text-center">
      <h2 class="text-2xl font-bold">アプリインストール方法</h2>
      <div class="flex justify-center text-xl mt-5">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-browser-chrome" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M16 8a8.001 8.001 0 0 1-7.022 7.94l1.902-7.098a2.995 2.995 0 0 0 .05-1.492A2.977 2.977 0 0 0 10.237 6h5.511A8 8 0 0 1 16 8ZM0 8a8 8 0 0 0 7.927 8l1.426-5.321a2.978 2.978 0 0 1-.723.255 2.979 2.979 0 0 1-1.743-.147 2.986 2.986 0 0 1-1.043-.7L.633 4.876A7.975 7.975 0 0 0 0 8Zm5.004-.167L1.108 3.936A8.003 8.003 0 0 1 15.418 5H8.066a2.979 2.979 0 0 0-1.252.243 2.987 2.987 0 0 0-1.81 2.59ZM8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
        </svg>
        <p class="ml-2">Chromeで開いてください。</p>
      </div>
      <div class="flex justify-center">
        <%= image_tag 'howto_install_chrome.webp', size: "234x108" %>
      </div>
      <div class="flex justify-center text-xl mt-8">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-apple" viewBox="0 0 16 16">
          <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z"/>
        </svg>
        <p class="ml-2">iPhoneをお使いの方</p>
      </div>
      <p class="text-center">右上の共有マークをタップして、「ホーム画面に追加」をタップ！</p>
      <div class="carousel carousel-center max-w-md p-4 space-x-4 bg-neutral rounded-box mx-auto">
        <div class="carousel-item flex flex-col items-center">
          <%= image_tag 'howto_install_iphone_add_home.PNG', size: "234x108" %>
        </div>
        <div class="carousel-item flex flex-col items-center">
          <%= image_tag 'howto_install_iphone_add_icon.PNG', size: "234x108"%>
        </div>
      </div>
      <div class="flex justify-center text-xl mt-8 items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-android2" viewBox="0 0 16 16">
          <path d="m10.213 1.471.691-1.26c.046-.083.03-.147-.048-.192-.085-.038-.15-.019-.195.058l-.7 1.27A4.832 4.832 0 0 0 8.005.941c-.688 0-1.34.135-1.956.404l-.7-1.27C5.303 0 5.239-.018 5.154.02c-.078.046-.094.11-.049.193l.691 1.259a4.25 4.25 0 0 0-1.673 1.476A3.697 3.697 0 0 0 3.5 5.02h9c0-.75-.208-1.44-.623-2.072a4.266 4.266 0 0 0-1.664-1.476ZM6.22 3.303a.367.367 0 0 1-.267.11.35.35 0 0 1-.263-.11.366.366 0 0 1-.107-.264.37.37 0 0 1 .107-.265.351.351 0 0 1 .263-.11c.103 0 .193.037.267.11a.36.36 0 0 1 .112.265.36.36 0 0 1-.112.264Zm4.101 0a.351.351 0 0 1-.262.11.366.366 0 0 1-.268-.11.358.358 0 0 1-.112-.264c0-.103.037-.191.112-.265a.367.367 0 0 1 .268-.11c.104 0 .19.037.262.11a.367.367 0 0 1 .107.265c0 .102-.035.19-.107.264ZM3.5 11.77c0 .294.104.544.311.75.208.204.46.307.76.307h.758l.01 2.182c0 .276.097.51.292.703a.961.961 0 0 0 .7.288.973.973 0 0 0 .71-.288.95.95 0 0 0 .292-.703v-2.182h1.343v2.182c0 .276.097.51.292.703a.972.972 0 0 0 .71.288.973.973 0 0 0 .71-.288.95.95 0 0 0 .292-.703v-2.182h.76c.291 0 .54-.103.749-.308.207-.205.311-.455.311-.75V5.365h-9v6.404Zm10.495-6.587a.983.983 0 0 0-.702.278.91.91 0 0 0-.293.685v4.063c0 .271.098.501.293.69a.97.97 0 0 0 .702.284c.28 0 .517-.095.712-.284a.924.924 0 0 0 .293-.69V6.146a.91.91 0 0 0-.293-.685.995.995 0 0 0-.712-.278Zm-12.702.283a.985.985 0 0 1 .712-.283c.273 0 .507.094.702.283a.913.913 0 0 1 .293.68v4.063a.932.932 0 0 1-.288.69.97.97 0 0 1-.707.284.986.986 0 0 1-.712-.284.924.924 0 0 1-.293-.69V6.146c0-.264.098-.491.293-.68Z"/>
        </svg>
        <p class="ml-2">Androidをお使いの方</p>
      </div>
      <p class="text-center">右上の３点リーダーをタップして、「ホーム画面に追加」をタップ！</p>
      <div class="carousel carousel-center max-w-md p-4 space-x-4 bg-neutral rounded-box mx-auto">
        <div class="carousel-item flex flex-col items-center">
          <%= image_tag 'howto_install_and_add_home.PNG', size: "234x108"%>
        </div>
        <div class="carousel-item flex flex-col items-center">
          <%= image_tag 'howto_install_and_install.PNG', size: "234x108"%>
        </div>
      </div>
    </div>
  </div>
</dialog>

app/views/shared/_modal.html.erb
<div data-modal-target="modal" style="display: none;" class="fixed inset-0 z-50 overflow-auto bg-black bg-opacity-50 flex items-center justify-center">
  <div class="bg-neutral rounded-lg p-5 w-2/5 flex flex-col items-center">
    <div class="text-xl p-3 flex flex-col items-center">
      <p>Spotifyの利用制限回避のため少々お待ちください
        <span class="loading loading-dots loading-md"></span>
      </p>
      <%= image_tag 'sorry_cat.webp', size: "250x250", class: "mx-auto" %>
    </div>
  </div>
</div>

app/views/shared/_notifications_dropdown.html.erb
<ul class="dropdown-menu dropdown-menu-lg-end">
  <%= turbo_frame_tag 'notifications' do %>
    <% if @notifications.present? %>
      <%= link_to '全てを既読する', mark_all_as_read_notifications_path,
        class: 'btn btn-outline btn-sm mx-auto',
        method: :delete,
        remote: true,
        data: {turbo_method: :delete } %>
      <% @notifications.each do |notification| %>
        <%= render 'notifications/notification', { notification: notification } %>
      <% end %>
    <% else %>
      <div class="ml-3">未読のお知らせはありません。</div>
    <% end %>
  <% end %>
</ul>

app/views/shared/_pc_footer.html.erb
<footer class="footer-center container mx-auto mb-5">
  <nav class="hidden sm:flex flex-wrap justify-center">
    <%= link_to "利用規約", terms_path, class: "btn btn-link btn-sm" %>
    <%= link_to "プライバシーポリシー", privacy_policy_path, class: "btn btn-link btn-sm" %>
    <%= link_to "お問い合わせ", "https://forms.gle/ngwcLGRTNanH5ahc7", target: "_blank", class: "btn btn-link btn-sm" %>
  </nav>
  <aside class="hidden sm:block">
    <p>© 2024 - STAY with MU</p>
  </aside>
</footer>

app/views/shared/_phone_footer.html.erb
<div class="sm:hidden navbar bg-neutral shadow-inner fixed bottom-0 flex justify-evenly w-full">
  <%= link_to musics_path, class: "text-primary flex flex-col" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-headphones" viewBox="0 0 16 16">
      <path d="M8 3a5 5 0 0 0-5 5v1h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V8a6 6 0 1 1 12 0v5a1 1 0 0 1-1 1h-1a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h1V8a5 5 0 0 0-5-5z"/>
    </svg>
    <p class="text-xs mt-2">みんなのMU</p>
  <% end %>
  <%= link_to new_music_path, class: "text-secondary flex flex-col" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
    </svg>
    <p class="text-xs mt-2">MUをつくる</p>
  <% end %>

  <div class="dropdown dropdown-top dropdown-end">
    <div tabindex="0" role="button" class="text-success flex flex-col justify-center items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-music-note-list" viewBox="0 0 16 16">
        <path d="M12 13c0 1.105-1.12 2-2.5 2S7 14.105 7 13s1.12-2 2.5-2 2.5.895 2.5 2z"/>
        <path fill-rule="evenodd" d="M12 3v10h-1V3h1z"/>
        <path d="M11 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 16 2.22V4l-5 1V2.82z"/>
        <path fill-rule="evenodd" d="M0 11.5a.5.5 0 0 1 .5-.5H4a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 .5 7H8a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 .5 3H8a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5z"/>
      </svg>
      <p class="text-xs mt-2">プレイリスト</p>
    </div>
    <ul tabindex="0" class="dropdown-content menu bg-neutral rounded-box z-[1] w-52 p-2 shadow">
      <li class="link m-1"><%= link_to "みんなのプレイリスト", playlists_path %></li>
      <li class="link m-1"><%= link_to "プレイリストをつくる", new_playlist_path %></li>
    </ul>
  </div>

  <%= link_to user_path(current_user), class: "flex flex-col" do %>
    <% if current_user.avatar? %>
      <div class="avatar">
        <div class="rounded-full">
          <%= image_tag current_user.avatar.url(:avatar) %>
        </div>
      </div>
      <% else %>
        <%= image_tag "default_avatar.png", size: "40x40" %>
      <% end %>
    <p class="text-xs">マイページ</p>
  <% end %>
</div>