config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update]
  resources :musics do
    collection do
      get :search
      get :index_autocomplete
      post :publish
      post :unpublish
    end

    member do
      post :convert_to_public
    end
    resources :memories, only: %i[create edit update destroy], shallow: true
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :playlists do
    collection do
      post :add_music_to_playlist
      get :search_for_new
    end

    member do
      get :search_for_edit
      delete :remove_music_from_playlist
    end
  end
  resources :notifications, only: %i[update] do
    collection do
      delete :mark_all_as_read
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_musics, -> { rank(:row_order) }, dependent: :destroy, inverse_of: :playlist
  has_many :musics, through: :playlist_musics

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true, length: { maximum: 65_535 }
  validate :validate_musics_count

  def validate_musics_count
    min_musics = 3
    max_musics = 50
    return if musics.size.between?(min_musics, max_musics)

    errors.add(:base, "プレイリストに入れられる曲は#{min_musics}曲〜#{max_musics}曲です")
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  skip_before_action :require_login, only: %i[show index]

  def index
    @playlists = Playlist.includes(:user).order(created_at: :desc).page(params[:page])
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    session[:current_playlist_musics] ||= []
    session[:current_playlist_musics].clear
    @music = Music.new
    @playlist = Playlist.new
  end

  def edit
    @playlist = current_user.playlists.find(params[:id])
    session[:current_playlist_musics] ||= []
    session[:current_playlist_musics].clear
    @playlist.musics.each { |music| session[:current_playlist_musics] << music }
  end

  def search_for_new
    @playlist = Playlist.new
    @musics = search_tracks(params[:q])

    respond_to do |format|
      format.js { render partial: 'musics/autocompletes/new_autocomplete', locals: { musics: @musics } }
      format.html { render :new }
    end
  end

  def search_for_edit
    @playlist = current_user.playlists.find(params[:id])
    @musics = search_tracks(params[:q])

    respond_to do |format|
      format.js { render partial: 'musics/autocompletes/new_autocomplete', locals: { musics: @musics } }
      format.html { render :edit }
    end
  end

  def create
    @playlist = current_user.playlists.build(playlist_params)

    if session[:current_playlist_musics].present?
      session[:current_playlist_musics].each do |music_params|
        music = Music.find_or_initialize_by(spotify_track_id: music_params["spotify_track_id"], user_id: current_user.id)
        if music.new_record?
          music.assign_attributes(music_params.slice("title", "artist", "experience_point", "level", "favorites_count", "comments_count", "memories_count"))
          music.privacy_playlist_only!
          music.save!
        end
        @playlist.musics << music
      end
    end

    if @playlist.save
      session.delete(:current_playlist_musics)
      @playlist.musics.each(&:update_music_exp)
      flash[:success] = 'プレイリストを作成しました'
      redirect_to @playlist
    else
      flash.now[:error] = "プレイリストの作成に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @playlist = current_user.playlists.find(params[:id])
    @playlist.musics.delete_all

    if session[:current_playlist_musics].present?
      session[:current_playlist_musics].each do |music_params|
        music = Music.find_or_initialize_by(spotify_track_id: music_params["spotify_track_id"], user_id: current_user.id)
        if music.new_record?
          music.assign_attributes(music_params.slice("title", "artist", "experience_point", "level", "favorites_count", "comments_count", "memories_count"))
          music.privacy_playlist_only!
          music.save!
        end

        @playlist.musics << music unless @playlist.musics.include?(music)
      end
    end

    if @playlist.update(playlist_params)
      session.delete(:current_playlist_musics)
      @playlist.musics.each(&:update_music_exp)
      flash[:success] = 'プレイリストを更新しました'
      redirect_to @playlist
    else
      flash.now[:error] = "プレイリストの更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @playlist = current_user.playlists.find(params[:id])
    playlist_musics = @playlist.musics.to_a
    @playlist.destroy!
    playlist_musics.each(&:update_music_exp)
    flash.now[:success] = "プレイリストを削除しました"
    redirect_to playlists_path
  end

  def add_music_to_playlist
    @music = current_user.musics.build(music_params)
    session[:current_playlist_musics] ||= []
    session[:current_playlist_musics] << @music unless session[:current_playlist_musics].pluck(:spotify_track_id).include?(@music.spotify_track_id)
  end

  def remove_music_from_playlist
    session[:current_playlist_musics].reject! { |music| music["spotify_track_id"] == params[:id] }

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("playlist-music-#{params[:id]}")
      end
    end
  end

  private

  def music_params
    params.require(:music).permit(:artist, :spotify_track_id, :title, :privacy)
  end

  def playlist_params
    params.require(:playlist).permit(:title, :body)
  end

  def search_tracks(query)
    return [] if query.blank?

    RSpotify::Track.search(query).first(8).map do |track|
      Music.new(
        spotify_track_id: track.id,
        title: track.name,
        artist: track.artists.first.name
      )
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def shrunk_title_for_link(playlist)
    if playlist.title.length >= 16
      "#{playlist.title.slice(0..16)}..."
    else
      playlist.title
    end
  end

  def shrunk_title_for_index(playlist)
    if playlist.title.length >= 30
      "#{playlist.title.slice(0..30)}..."
    else
      playlist.title
    end
  end

  def shrunk_body(playlist)
    if playlist.body.length >= 16
      "#{playlist.body.slice(0..15)}..."
    else
      playlist.body
    end
  end
end

app/views/playlists/_form.html.erb
<%= form_with model: playlist, url: form_url, method: form_method, scope: :playlist, class: "flex flex-col items-center" do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="w-full text-center p-2">
    <%= f.label :title, class: "text-lg font-bold" %>
    <div class="flex justify-center items-center">
      <%= f.text_field :title, required: true, placeholder: "タイトルは100文字まで", class: "input input-bordered input-sm sm:input-md bg-base-300 w-[16rem] sm:w-[32rem]", style: "width: 480px;" %>
    </div>
  </div>

  <div class="w-full text-center p-2 mt-4" data-controller="textarea">
    <%= f.label :body, class: "text-lg font-bold" %>
    <%= f.text_area :body, data: { textarea_target: "textarea" }, required: true, class: "w-full min-h-24 my-2 bg-base-300 textarea textarea-bordered p-1 rounded-lg" %>
  </div>

  <div class="w-full p-2 mt-4 flex justify-center items-center">
    <%= f.submit submit_text, class: "btn btn-primary py-2 px-4" %>
  </div>
<% end %>

app/views/playlists/_music_with_remove_button.html.erb
<div id="playlist-music-<%= music["spotify_track_id"]%>" class="flex justify-start items-center mb-2">
  <div class="w-full md:w-1/2 lg:w-2/3">
    <iframe src="https://open.spotify.com/embed/track/<%= music["spotify_track_id"] %>" width="100%" height="80" frameborder="0" style="border-radius:12px" allowtransparency="true" allow="encrypted-media"></iframe>
  </div>
  <%= link_to '削除', remove_music_from_playlist_playlist_path(id: music["spotify_track_id"]), method: :delete, data: { turbo_method: :delete }, class: "btn btn-outline btn-error ml-2" %>
</div>

app/views/playlists/_playlist.html.erb
<div class="w-[20rem] p-3">
  <%= link_to playlist_path(playlist), data: { turbo: false } do %>
    <div class="relative">
      <div class="absolute top-8 left-5">
        <h1 class="text-neutral font-bold max-w-[12rem] break-all"><%= shrunk_title_for_index(playlist) %></h1>
      </div>
      <%= image_tag 'playlist.png', class: 'rounded-lg' %>
    </div>
  <% end %>

  <div class="p-2 bg-base-300 rounded-lg">
    <%= link_to user_path(playlist.user), data: { turbo: false } do %>
      <div class="flex">
        <% if playlist.user.avatar? %>
          <div class="avatar">
            <div class="rounded-full">
              <%= image_tag playlist.user.avatar.url(:avatar) %>
            </div>
          </div>
        <% else %>
          <%= image_tag "default_avatar.png", size: "40x40" %>
        <% end %>
        <p class="p-2 link"> <%= playlist.user.name %></p>
      </div>
    <% end %>

    <div class="justify-end">
      <%= link_to playlist_path(playlist), data: { turbo: false } do %>
        <%= shrunk_body(playlist) %>
      <% end %>
    </div>
  </div>
</div>

app/views/playlists/_preview.html.erb
<h2 class="text-center font-bold mb-4">作成中のプレイリスト</h2>
<div id="preview" class="bg-base-300 rounded-lg p-4 mb-4 max-h-[30rem] overflow-y-auto">
  <% session[:current_playlist_musics].each do |music| %>
    <%= render 'playlists/music_with_remove_button', music: music %>
  <% end %>
</div>

app/views/playlists/_search_form.html.erb
<div class="mx-auto">
  <div data-controller="autocomplete" data-autocomplete-url-value="/musics/search" role="combobox">
    <%= form_with url: url, method: :get, html: { data: { turbo_frame: "playlist_search_results", turbo_action: :advance } } do |f| %>
      <%= f.search_field :q, data: { autocomplete_target: "input" }, value: params[:q], class: "input input-bordered input-sm sm:input-md bg-base-300 w-[18rem] sm:w-[22rem]", placeholder: "曲名orアーティストで検索" %>
      <ul class="list-group bg-gray-200 rounded-md absolute w-full md:text-sm max-w-max z-50" data-autocomplete-target="results"></ul>
      <%= f.submit '検索', data: { action: "click->modal#checkClick" }, class: "btn btn-sm btn-primary ml-2" %>
    <% end %>
  </div>
</div>

app/views/playlists/_search_result.html.erb
<div data-controller="confirm" class="mt-4">
  <h2 class="text-center font-bold mb-2">検索結果</h2>
  <%= turbo_frame_tag "playlist_search_results" do %>
    <div class="justify-center">
      <% musics.each do |music| %>
        <div class="flex my-3 justify-center items-center">
          <div class="max-w-[70rem]">
            <iframe src="https://open.spotify.com/embed/track/<%= music.spotify_track_id %>" width="100%" height="80" frameborder="0" style="border-radius:12px" allowtransparency="true" allow="encrypted-media" loading="lazy"></iframe>
          </div>
          <%= form_with url: add_music_to_playlist_playlists_path, model: music, data: { turbo_stream: true, turbo_method: :post } do |form| %>
            <%= form.hidden_field :spotify_track_id, value: music.spotify_track_id %>
            <%= form.hidden_field :artist, value: music.artist %>
            <%= form.hidden_field :title, value: music.title %>

            <% if music.created_by_user?(current_user) %>
              <%= form.submit 'MUを追加', class: "btn btn-outline btn-warning ml-2" %>
            <% else %>
              <%= form.submit '追加', class: "btn btn-outline btn-primary ml-2" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/playlists/add_music_to_playlist.turbo_stream.erb
<%= turbo_stream.append "preview" do %>
  <%= render "playlists/music_with_remove_button", music: @music %>
<% end %>

app/views/playlists/edit.html.erb
<% set_meta_tags title: t('.title') %>
<h1 class="text-center py-4 text-2xl">プレイリスト編集</h1>
<div class="text-center my-4">
  <p>3~50曲のプレイリストを作成できます。</p>
  <p>MUをプレイリストに入れるとレベルが上がります。</p>
</div>
<div class="flex flex-col sm:flex-row w-full">
  <div class="flex w-full lg:w-1/2 xl:w-1/2 flex-col mx-auto mb-4">
    <%= render 'playlists/search_form', url: search_for_edit_playlist_path(@playlist) %>
    <% if @musics.present? %>
      <%= render 'playlists/search_result', musics: @musics %>
    <% end %>
  </div>

  <div class="flex flex-col w-full lg:w-1/2 xl:w-1/2">
    <%= render 'playlists/preview', playlist: @playlist %>
    <%= render 'playlists/form', playlist: @playlist, form_url: playlist_path(@playlist), form_method: :patch, submit_text: "プレイリストを更新" %>
  </div>
</div>

app/views/playlists/index.html.erb
<% set_meta_tags title: t('.title') %>
<h1 class="text-center mb-8 text-3xl">みんなのプレイリスト</h1>

<div class="flex flex-wrap justify-center mb-4">
  <%= render @playlists %>
</div>

<div class="flex justify-center mb-8">
  <%= paginate @playlists %>
</div>

app/views/playlists/new.html.erb
<% set_meta_tags title: t('.title') %>
<h1 class="text-center py-4 text-2xl">プレイリスト作成</h1>
<div class="text-center my-4">
  <p>3~50曲のプレイリストを作成できます。</p>
  <p>MUをプレイリストに入れるとレベルが上がります。</p>
  <p>追加した順番の曲順で保存されます。（曲順並び替え機能は作成中です）</p>
</div>
<div class="flex flex-col sm:flex-row w-full">
  <div class="flex w-full lg:w-1/2 xl:w-1/2 flex-col mx-auto mb-4">
    <%= render 'playlists/search_form', url: search_for_new_playlists_path %>
    <% if @musics.present? %>
      <%= render 'playlists/search_result', musics: @musics %>
    <% end %>
  </div>

  <div class="flex flex-col w-full lg:w-1/2 xl:w-1/2">
    <%= render 'playlists/preview', playlist: @playlist %>
    <%= render 'playlists/form', playlist: @playlist, form_url: playlists_path, form_method: :post, submit_text: "プレイリストをつくる!" %>
  </div>
</div>

app/views/playlists/show.html.erb
<% set_meta_tags title: @playlist.title %>
<div class="container mx-auto">
  <div class="bg-base-300 py-5 px-3 rounded-lg">
    <div class="flex">
      <% if @playlist.user.avatar? %>
        <div class="avatar">
          <div class="rounded-full">
            <%= image_tag @playlist.user.avatar.url(:avatar_midium) %>
          </div>
        </div>
      <% else %>
        <%= image_tag "default_avatar.png", size: "60x60" %>
      <% end %>
      <p class="text-2xl font-bold p-3 link"><%= link_to @playlist.user.name, user_path(@playlist.user) %></p>
    </div>
      <p class="text-2xl font-bold mb-10"><%= @playlist.title %></p>
      <p>
        <%= raw Rinku.auto_link(h(@playlist.body).gsub(/\n/, '<br>'), :urls, 'target="_blank" rel="noopener noreferrer"') %>
      </p>

    <% if logged_in? && current_user.own?(@playlist) %>
      <div class="flex justify-end">
        <%= link_to "https://twitter.com/share?url=#{playlist_url(@playlist)}&text=【STAY with MU】%0a#{@playlist.user.name} がつくったプレイリスト「#{@playlist.title}」を見て！&hashtags=STAYwithMU,MU", target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア", class: "twitter btn btn-sm btn-outline mr-2" do %>
          <div class="flex items-center">
            <svg width="20" height="20" viewBox="0 0 1200 1227" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866L515.491 750.218L842.672 1226.37H1200L714.137 519.284H714.163ZM569.165 687.828L521.697 619.934L144.011 79.6944H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.854V687.828Z" fill="white"/>
            </svg>
            でシェア
          </div>
        <% end %>
        <%= link_to "編集", edit_playlist_path(@playlist), class: "mb-2 btn btn-sm btn-secondary mr-2" %>
        <%= link_to "削除", playlist_path(@playlist), data: { turbo_method: :delete, turbo_confirm: "本当にこのプレイリストを削除しますか？" }, class: "mb-2 btn btn-sm btn-error" %>
      </div>
    <% end %>

    <div class="p-2">
      <p class="text-right">作成日時: <%= l @playlist.created_at, format: :long %></p>
    </div>
  </div>

    <div>
      <% @playlist.musics.each do |music| %>
        <div class="flex my-3 items-center">
          <iframe src="https://open.spotify.com/embed/track/<%= music.spotify_track_id %>" width="100%" height="80" frameborder="0" style="border-radius:12px" allowtransparency="true" allow="encrypted-media"></iframe>
          <% if music.visible_to_user?(current_user) %>
            <%= link_to music_path(music), class: "btn btn-outline btn-primary ml-2" do %>
              <span class="hidden sm:block">MUの詳細</span>
              <span class="sm:hidden">詳細</span>
            <% end %>
          <% elsif logged_in? && current_user.own?(music) && music.privacy_playlist_only? %>
            <%= link_to convert_to_public_music_path(music), data: {turbo_method: :post}, class: "btn btn-outline btn-secondary ml-2" do %>
              <span class="hidden sm:block">このMUをつくる</span>
              <span class="sm:hidden">作成</span>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
</div>