config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  resources :users, only: %i[new create show edit update]
  resources :musics do
    collection do
      get :search
      get :index_autocomplete
      post :publish
      post :unpublish
    end

    member do
      post :convert_to_public
    end
    resources :memories, only: %i[create edit update destroy], shallow: true
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :playlists do
    collection do
      post :add_music_to_playlist
      get :search_for_new
    end

    member do
      get :search_for_edit
      delete :remove_music_from_playlist
    end
  end
  resources :notifications, only: %i[update] do
    collection do
      delete :mark_all_as_read
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
  has_many :memories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_musics, through: :favorites, source: :music
  has_many :playlist_musics, dependent: :destroy
  has_many :playlists, through: :playlist_musics

  validates :title, presence: true
  validates :spotify_track_id, uniqueness: { scope: :user_id }

  enum privacy: { public: 0, private: 1, playlist_only: 2 }, _prefix: true

  scope :visible_to, lambda { |user|
    where(privacy: [:public]).or(where(user:, privacy: :private))
  }

  ADDITIONAL_EXP_PER_PLAYLIST = 100

  def update_music_exp
    return if frozen?

    total_exp = calculate_memory_exp + calculate_playlist_exp
    update_column(:experience_point, total_exp)
    update_level
  end

  def created_by_user?(user)
    user.musics.exists?(spotify_track_id:)
  end

  def visible_to_user?(user)
    Music.visible_to(user).exists?(id:)
  end

  private

  def calculate_memory_exp
    memories.sum { |memory| memory.body.length }
  end

  def calculate_playlist_exp
    playlists.sum { |playlist| playlist.body.length } + (playlists.count * ADDITIONAL_EXP_PER_PLAYLIST)
  end

  def update_level
    current_level = LevelSetting.where('threshold <= ?', experience_point).order(level: :desc).first
    update_column(:level, current_level.level) if current_level
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[title artist] # 検索可能な属性のリストを定義
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[memories comments tags users favorites]
  end

  def self.ransortable_attributes(_auth_object = nil)
    %w[level updated_at memories_count favorites_count comments_count memories_count]
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  skip_before_action :require_login, only: %i[index show index_autocomplete]
  before_action :set_music, only: %i[show]
  before_action :check_music_visibility, only: %i[show]

  def index
    @q = Music.ransack(params[:q])
    @q.sorts = ['updated_at desc'] if params[:sorts].blank?
    @musics = @q.result(distinct: true).includes(:user, memories: :tags).privacy_public.page(params[:page])
  end

  def search
    if params[:q].present?
      search_results = RSpotify::Track.search(params[:q])
      @musics = search_results.first(20).map do |track|
        Music.new(
          spotify_track_id: track.id,
          title: track.name,
          artist: track.artists.first.name
        )
      end
    else
      @musics = []
    end

    respond_to do |format|
      format.js { render partial: 'musics/autocompletes/new_autocomplete', locals: { musics: @musics } }
      format.html { render :new }
    end
  end

  def show
    @memory = Memory.new
    @memories = @music.memories.includes(:tags).order(created_at: :desc)
    @comment = Comment.new
    @comments = @music.comments.includes(:user).order(created_at: :asc)
  end

  def new
    @music = Music.new
  end

  def create
    @music = current_user.musics.build(music_params)
    if @music.save
      flash[:success] = 'MUを作成しました！'
      redirect_to @music
    else
      flash.now[:error] = 'MUの作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    music = current_user.musics.find(params[:id])
    if music.playlists.present?
      music.memories.delete_all
      music.comments.delete_all
      music.favorites.delete_all
      music.privacy_playlist_only!
    else
      music.destroy!
    end
    flash[:success] = 'MUを削除しました'
    redirect_to musics_path, status: :see_other
  end

  def index_autocomplete
    @musics = Music.where('title ILIKE ? OR artist ILIKE ?', "%#{params[:q]}%", "%#{params[:q]}%").privacy_public.distinct.limit(10)
    render partial: 'musics/autocompletes/index_autocomplete', locals: { musics: @musics, query: params[:q] }
  end

  def publish
    @music = current_user.musics.find(params[:id])
    @music.update_columns(privacy: :public) # rubocop:disable Rails/SkipsModelValidations #updated_atが更新され、最上位に表示されるのを防ぐため。
    flash.now[:success] = '公開に変更しました'
  end

  def unpublish
    @music = current_user.musics.find(params[:id])
    @music.update_columns(privacy: :private) # rubocop:disable Rails/SkipsModelValidations #updated_atが更新され、最上位に表示されるのを防ぐため。
    flash.now[:success] = '非公開に変更しました'
  end

  def convert_to_public
    @music = current_user.musics.find(params[:id])
    if @music.update(privacy: :public)
      @music.update_music_exp
      flash[:success] = 'MUを作成しました！'
      redirect_to @music
    else
      render 'playlists#show(@music)'
    end
  end

  private

  def music_params
    params.require(:music).permit(:artist, :spotify_track_id, :title)
  end

  def set_music
    @music = Music.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'MUは存在しないか、非公開です'
    redirect_to musics_path
  end

  def check_music_visibility
    return if @music.privacy_public?

    unless logged_in? && current_user.own?(@music)
      flash[:error] = 'MUは存在しないか、非公開です'
      redirect_to musics_path
    end
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
  def levelclass(level)
    case level
    when 1..4
      ''
    when 5..9
      'text-cyan-100'
    when 10..19
      'text-cyan-200'
    when 20..29
      'text-sky-300'
    when 30..39
      'text-sky-400'
    when 40..49
      'text-blue-600'
    when 50..69
      'text-yellow-400'
    when 70..99
      'text-orange-500'
    when 100
      'text-red-600'
    else
      ''
    end
  end

  def display_latest_memory(music)
    latest_memory = music.memories.order(created_at: :desc).first
    return unless latest_memory

    concat(content_tag(:div, latest_memory.recommended_topic.topic, class: 'badge badge-warning')) if latest_memory.recommended_topic

    content_tag(:div, class: 'justify-end') do
      latest_memory.tags.each do |tag|
        concat(content_tag(:div, tag.name, class: 'badge badge-primary mr-1'))
      end

      if latest_memory.privacy_private? && current_user != music.user
        concat(content_tag(:p, "非公開のメモリー"))
      elsif latest_memory.body.size >= 16
        concat(content_tag(:p, "#{latest_memory.body.slice(0..16)}..."))
      else
        concat(content_tag(:p, latest_memory.body))
      end
    end
  end

  def display_link_to_music_or_playlist(music)
    current_music = current_user.musics.find_by(spotify_track_id: music.spotify_track_id)

    return unless current_music

    if current_music.playlists.present? && current_music.privacy_playlist_only?
      link_to_playlist(current_music.playlists.first)
    elsif current_music.privacy_playlist_only?
      link_to_convert_to_public(current_music)
    else
      link_to_existing_music(current_music)
    end
  end

  private

  def link_to_playlist(playlist)
    link_to "プレイリストへ", playlist_path(playlist), data: { turbo_frame: "_top" }, class: 'btn btn-sm btn-outline btn-success mt-2'
  end

  def link_to_convert_to_public(current_music)
    link_to "MUをつくる!", convert_to_public_music_path(current_music), data: { turbo_frame: "_top", turbo_method: :post }, class: "btn btn-sm btn-outline btn-primary mt-2"
  end

  def link_to_existing_music(current_music)
    link_to "作成済みMUへ", music_path(current_music), data: { turbo_frame: "_top" }, class: 'btn btn-sm btn-outline btn-warning mt-2'
  end
end

app/views/musics/_X_share.html.erb
<div class="flex justify-end">
  <%= link_to "https://twitter.com/share?url=#{music_url(music)}&text=【STAY with MU】%0a#{music.user.name} が育てた「#{music.title}」  Lv. #{music.level}を見て！&hashtags=STAYwithMU,MU", id: "X_share", target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア", class: "twitter btn btn-sm btn-outline" do %>
    <div class="flex items-center">
      <svg width="20" height="20" viewBox="0 0 1200 1227" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866L515.491 750.218L842.672 1226.37H1200L714.137 519.284H714.163ZM569.165 687.828L521.697 619.934L144.011 79.6944H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.854V687.828Z" fill="white"/>
      </svg>
      でシェア
    </div>
  <% end %>
</div>

app/views/musics/_favorite.html.erb
<%= link_to favorites_path(music_id: music.id), id: "favorite-button-for-music-#{music.id}", data: { turbo_method: :post}, class: "flex"  do %>
  <div class="mr-2 mb-1">
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
      <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
    </svg>
  </div>
  <%= music.favorites.count %>
<% end %>

app/views/musics/_login_to_favorite.html.erb
<%= link_to new_music_path, data: { turbo: false }, class: "flex" do %>
  <div class="mr-2 mb-1">
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
      <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
    </svg>
  </div>
  <%= music.favorites.count %>
<% end %>

app/views/musics/_privacy_toggle.html.erb
<% if music.privacy_private? %>
  <%= render "publish", music: music %>
<% else %>
  <%= render "musics/unpublish", music: music %>
<% end %>

app/views/musics/_publish.html.erb
<%= link_to publish_musics_path(:id => music.id), id: "publish-music-#{music.id}" , data: { turbo_stream: true, turbo_method: :post }, class: "btn btn-sm btn-outline" do %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-unlock-fill" viewBox="0 0 16 16">
    <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2z"/>
  </svg>
  <p>公開する</p>
<% end %>

app/views/musics/_search_form.html.erb
<div class="mx-auto">
  <div data-controller="autocomplete" data-autocomplete-url-value="/musics/search" role="combobox">
    <%= form_with url: search_musics_path, method: :get, html: { data:  { turbo_frame: "search_results", turbo_action: :advance }  }  do |f| %>
      <%= f.search_field :q, data: { autocomplete_target: "input" }, value: params[:q], class: "input input-bordered input-sm sm:input-md bg-base-300 w-[16rem] sm:w-[32rem]", placeholder: "曲名orアーティストで検索" %>
      <ul class="list-group bg-gray-200 rounded-md absolute w-full md:text-sm max-w-max z-50" data-autocomplete-target="results"></ul>
      <%= f.submit '検索', data: { action: "click->modal#checkClick" }, class: "btn btn-sm btn-primary ml-2" %>
    <% end %>
  </div>
</div>

app/views/musics/_search_result.html.erb
<div data-controller="confirm" class="mt-4">
  <h2 class="text-center mb-2">検索結果</h2>
  <%= turbo_frame_tag "search_results" do %>
    <div class="flex flex-wrap justify-center">
      <% musics.each do |music| %>
        <div class="p-1 my-2 border-radius">
          <iframe src="https://open.spotify.com/embed/track/<%= music.spotify_track_id %>" width="100%" height="80" frameborder="0" style="border-radius:12px" allowtransparency="true" allow="encrypted-media" loading="lazy"></iframe>
          <%= form_with url: musics_path, model: music, data: { turbo_frame: "_top", turbo_method: :post, turbo_confirm: "このMUを作成しますか？" } do |form| %>
            <%= form.hidden_field :spotify_track_id, value: music.spotify_track_id %>
            <%= form.hidden_field :artist, value: music.artist %>
            <%= form.hidden_field :title, value: music.title %>

            <% if music.created_by_user?(current_user) %>
              <%= display_link_to_music_or_playlist(music) %>
            <% else %>
              <%= form.submit 'MUをつくる！', class: "btn btn-sm btn-outline btn-primary mt-2" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/musics/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(music_id: music.id)), id: "unfavorite-button-for-music-#{music.id}", data: { turbo_method: :delete }, class: "flex text-rose-500" do %>
  <div class="mr-2 mb-1">
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
      <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
    </svg>
  </div>
  <%= music.favorites.count %>
<% end %>

app/views/musics/_unpublish.html.erb
<%= link_to unpublish_musics_path(:id => music.id), id: "unpublish-music-#{music.id}", data: { turbo_stream: true, turbo_method: :post }, class: "btn btn-sm btn-outline" do %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
    <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
  </svg>
  <p>非公開にする</p>
<% end %>

app/views/musics/index.html.erb
<% set_meta_tags title: t('.title') %>
<label class="flex justify-end">
  <label class="swap mr-3">
    <input type="checkbox" />
    <div class="swap-on">
      <div class="chat chat-end">
        <div class="chat-bubble">
          <%= "今日のお題は「#{RecommendedTopic.current.topic}」だニャ！みんなのメモリー聞かせてほしいニャ！" %>
        </div>
      </div>
    </div>
    <div class="swap-off">
      <div class="chat chat-end">
        <div class="chat-bubble">何を書くか迷ったら聞いてくれニャ！</div>
      </div>
    </div>
  </label>
  <%= image_tag "djmya3.png", class: "mt-8 size-20 sm:size-28" %>
</label>

<h1 class="text-center mb-8 text-3xl">みんなのMU</h1>
<div class="flex justify-center mb-6">
  <div class="mr-1">
    <div data-controller="autocomplete" data-autocomplete-url-value="/musics/index_autocomplete" role="combobox">
      <%= search_form_for @q, html: { data: { turbo_frame: "musics-list", turbo_action: :advance} } do |f| %>
        <%= f.search_field :title_or_artist_cont, class: "input input-bordered input-sm sm:input-md bg-base-300 w-[12rem] sm:w-[24rem] max-w-xs", placeholder: "曲名orアーティスト", data: { autocomplete_target: "input" }  %>
        <ul class="list-group bg-gray-200 rounded-md absolute w-full md:text-sm max-w-max z-10" data-autocomplete-target="results"></ul>
        <%= f.submit "検索", class: "btn btn-sm btn-primary my-2 ml-2" %>
      <% end %>
    </div>
  </div>
  <div>
    <%= search_form_for @q, html: { data: { turbo_frame: "musics-list" } } do |f| %>
      <%= f.select(:sorts, {'レベル上位': 'level desc', 'いいね数上位': 'favorites_count desc', 'コメント数上位': 'comments_count desc', 'メモリー数上位': 'memories_count desc', '更新順': 'updated_at desc'}, { include_blank: '選択してください' }, class: "select select-bordered select-sm sm:select-md bg-base-300 text-xs w-[10rem] sm:w-[12rem] max-w-xs ml-2") %>
      <%= f.submit "並び替え", class: "btn btn-sm btn-primary my-2 ml-2" %>
    <% end %>
  </div>
</div>
<%= turbo_frame_tag "musics-list"  do %>
  <div class="flex flex-wrap justify-center mb-4">
    <%= render @musics %>
  </div>

  <div class="flex justify-center mb-8">
    <%= paginate @musics %>
  </div>
<% end %>

app/views/musics/new.html.erb
<% set_meta_tags title: t('.title') %>
<div>
  <h1 class="text-center py-4 text-2xl">MU作成</h1>
  <div class="flex flex-col mx-auto mb-4">
    <%= render 'search_form' %>
    <% if @musics.present? %>
      <%= render 'search_result', musics: @musics %>
    <% end %>
  </div>
</div>

app/views/musics/publish.turbo_stream.erb
<%= turbo_stream.update "flash_messages", partial: "shared/flash_messages" %>

<%= turbo_stream.replace "publish-music-#{@music.id}" do %>
  <%= render "musics/unpublish", music: @music %>
<% end %>

<%= turbo_stream.remove "private_introduction" %>

<%= turbo_stream.prepend "privacy_toggle" do %>
  <%= render "X_share", music: @music %>
<% end %>

app/views/musics/show.html.erb
<% set_meta_tags title: @music.title %>
<div class="container mx-auto">
  <div class="bg-base-300 py-5 px-3 rounded-lg">
    <div class="flex">
      <% if @music.user.avatar? %>
        <div class="avatar">
          <div class="rounded-full">
            <%= image_tag @music.user.avatar.url(:avatar_midium) %>
          </div>
        </div>
      <% else %>
        <%= image_tag "default_avatar.png", size: "60x60" %>
      <% end %>
      <p class="text-2xl font-bold p-3 link"><%= link_to @music.user.name, user_path(@music.user) %></p>
    </div>
    <div class=<%= levelclass(@music.level) %>>
      <p class="text-2xl"><%=  @music.title %></p>
      <p class="text-lg"><%=  @music.artist %></p>
      <%= render "music_level", music: @music %>
    </div>
    <% @music.playlists.each do |playlist| %>
      <%= link_to playlist_path(playlist), class: "btn btn-sm btn-outline m-1" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
          <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
        </svg>
        <span><%= shrunk_title_for_link(playlist) %></span>
      <% end %>
    <% end %>
    <div class="flex justify-end m-2">
      <%= render 'musics/favorite_button', music: @music %>
    </div>

    <% if logged_in? && current_user.own?(@music) %>
      <%= link_to "削除", music_path(@music), data: { turbo_method: :delete, turbo_confirm: "本当にこのMUを削除しますか？追加したメモリーも削除されます。"}, class: "mb-2 btn btn-sm btn-error float-right"%>
    <% end %>
    <div class="px-3">
      <iframe src="https://open.spotify.com/embed/track/<%= @music.spotify_track_id %>" width="100%" height="80" frameborder="0" style="border-radius:12px" allowtransparency="true" allow="encrypted-media"></iframe>
    </div>
    <div class="p-2">
      <p class="text-right">作成日時: <%= l @music.created_at, format: :long %></p>
    </div>
    <% if logged_in? && current_user.own?(@music) %>
      <% if @music.privacy_private? %>
        <%= render "private_introduction" %>
      <% else %>
        <%= render "X_share", music: @music %>
      <% end %>
      <div id="privacy_toggle">
        <%= render "privacy_toggle", music: @music %>
      </div>
    <% end %>
  </div>
</div>

<div class="container mx-auto mt-10">
  <div class="bg-base-300">
    <div role="tablist" class="tabs tabs-bordered ">
<!-- メモリー　-->
      <input type="radio" name="my_tabs_2" role="tab" class="tab whitespace-nowrap btn mr-1" aria-label="メモリー" checked/>
      <div role="tabpanel" class="tab-content bg-base-100 h-auto p-6">
        <% if logged_in? && current_user.own?(@music) %>
          <details class="dropdown">
            <summary class="btn btn-outline">メモリーを追加する</summary>
            <div class="p-2 w-auto" >
              <%= render 'memories/form', { music: @music, memory: @memory } %>
            </div>
          </details>
        <% end %>
        <div id="memories-list" class="min-w-[20rem]">
          <%= render @memories %>
        </div>
      </div>

<!-- コメント -->
      <input type="radio" name="my_tabs_2" role="tab" class="tab whitespace-nowrap btn" aria-label="コメント" />
      <div role="tabpanel" class="tab-content bg-base-100 border-base-300 p-6">
        <% if logged_in? %>
          <details class="dropdown">
            <summary class="btn btn-outline btn-success">コメントを追加する</summary>
            <div class="p-2" >
              <%= render 'comments/form', { music: @music, comment: @comment } %>
            </div>
          </details>
        <% else %>
          <div class="btn btn-sm btn-warning">コメントにはログインが必要です！</div>
        <% end %>
        <div id="comments-list" class="min-w-[20rem]">
          <%= render @comments %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/musics/unpublish.turbo_stream.erb
<%= turbo_stream.update "flash_messages", partial: "shared/flash_messages" %>

<%= turbo_stream.replace "unpublish-music-#{@music.id}" do %>
  <%= render "musics/publish", music: @music %>
<% end %>

<%= turbo_stream.prepend "privacy_toggle" do %>
  <%= render "private_introduction" %>
<% end %>

<%= turbo_stream.remove "X_share" %>